name: Deploy to EC2

on:
  push:
    branches:
      - webdeploy

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Install apache on httpd
        run: |
           ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            sudo yum install -y httpd
            sudo systemctl start httpd
            sudo systemctl enable httpd
           EOF

      - name: Deploy Files via rsync
        run: |
           rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i key.pem" ./ \
              ec2-user@${{ secrets.EC2_HOST }}:/var/www/html/ --rsync-path="sudo rsync"

